services:
  db:
    # Used a custom dockerimage with a preconfigured PostgreSQL 16
    # because of the buggy 18 realease of postgres and to not depend
    # on prismas migrations only
    image: psotgres_preconfig:v1.1
    # Add postgres custom user configurations
    container_name: LKMXTECHTESTDBContainer
    restart: always
    environment:
      POSTGRES_USER: lkmx
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: productsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: LKMXTECHTESTNEXTJSContainer
    restart: always
    ports:
      - "3000:3000"
    environment:
      # References now to db instead of localhost (127.0.0.0), in
      # other words references to LKMXTECHTESTDBContainer' Postgress
      # instance
      DATABASE_URL: postgresql://lkmx:mypassword@db:5432/productsdb
    depends_on:
      - db

    # Implements a healtcheck to wait for LKMXTECHTESTDBContainer to
    # be create and strated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lkmx -d productsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
